---
fontsize: 12pt
geometry: margin=0.75in
output: html_document
---
<!--```{r fig.width=5, fig.height=1,fig.align="center",echo=FALSE, warning=FALSE}

library(png)
library(grid)
img <- readPNG("X:/Claire/EFH literature/Reef Fish/Red Snapper/species profile/redsnapper.png")
 grid.raster(img)
```-->

###Red Snapper (*Lutjanus campechanus*)


####Distribution

Red snapper occur throughout the Gulf of Mexico (Gulf) shelf. They are particularly abundant on the Campeche Banks and in the northern Gulf. The species is demersal and is found over sandy and rocky bottoms, around reefs, and underwater objects from shallow water to 200 m, and possibly even beyond 1200 m. Adults favor deeper water in the northern Gulf. Spawning occurs in offshore waters from May to October at depths of 18 to 37 m over fine sand bottom away from reefs. Eggs are found offshore in summer and fall. Larvae, postlarvae and early juveniles are found July through November in shelf waters ranging in depth of 17 to 183 m. Early and late juveniles are often associated with structures, objects or small burrows, but also are abundant over barren sand and mud bottom. Late juveniles are taken year round at depths of 20 to 46 m. Adults are concentrated off Yucatan, Texas, and Louisiana at depths of 7 to 146 m and are most abundant at depths of 40 to 110 m. They commonly occur in submarine gullies and depressions, and over coral reefs, rock outcroppings, and gravel bottoms. 

####New literature review

New literature on red snapper is published frequently. This review yielded several papers that helped to fill gaps relating to red snapper habitat for a variety of life stages. Gallaway et al. (2009) wrote a review paper highlighting many details about red snapper life history. They cite Rabalais et al. (1980) and Minton et al. (1983) who found that approximately 50% of eggs hatch within 20-27 hours of fertilization. Gallaway et al. (2009) also cited Gallaway et al. (1999) who found the highest densities of juveniles red snapper at depths of 18-55 m. Kraus et al. (2006) evaluated the reef fish community on a mid-shelf bank (Sonnier Bank) in eco-region (ER) four and observed adult red snapper, highlighting a new habitat type used by that life stage. Several studies examined adults to identify season, depth, temperature and locations used during spawning. Kulaw (2012) examined reproductive biology of female red snapper on natural shelf-edge banks, and both standing and toppled petroleum platforms, and found that 50% maturity was reached at age 3-5 and 400-450 mm total length (TL), and all females were mature at age 8 and 700 mm TL. Fitzhugh et al. (2004) also studied reproduction in red snapper and determined that spawning occurs from April through October based on observations of females with hydrated ova and via gonadosomatic index values. They also found spawning occurred at depths from 30-126 m and temperatures of 16-29&deg;C. More habitat information has become available for juvenile red snapper since 2004 when the habitat association tables were last updated. Rooker et al. (2004) studied juvenile red snapper on bank and soft bottom habitats in ER-5. They found settlement size to be 16-19 mm SL, growth rates between 0.817-0.830 mm/d, and estimated a pelagic larval duration of 28 days. Szedlmayer and Lee (2004) examined diet shifts in juveniles and found that early juveniles fed on shrimp, chaetognaths, squid and copepods, and late juveniles fed on fish, squid, crabs and shrimp. They also noted collection of juveniles from waters with temperatures between 20-28&deg;C and salinities of 30-35 ppt. According to Szedlmayer and Mudrak (2014), dissolved oxygen < 0.4 mg/L caused a loss of juvenile red snapper on artificial reefs. The last new study on juveniles was conducted by Wells et al. (2008) who examined the effect of trawling on juveniles red snapper habitat and life history. They quantified growth rates over various habitat types and found that fish collected on sand habitats had the highest average growth at 1.01 mm/d. The last new piece of literature was the SEDAR 31 (2015) update assessment of red snapper which estimated an average mortality for age 2+ = 0.094/yr, age 1 = 1.2/yr, and age 0 = 2.0/yr.  The assessment also provided von Bertalanffy growth parameters; L~inf~ (max. TL cm) = 85.64, *K* = 0.19, and t~0~ = -0.39, and a maximum age = 48 years.. They also reported a batch fecundity estimate of 27-142 eggs/g fish weight.

  
####Habitat informaiton by life stage (see Habitat Association Tables in appendix A for references)

  *Eggs:*
   
Eggs are found throughout the Gulf and are water column associated. They occur in offshore waters from depths of 18-126 m (based on spawning adult depth distributions) and have a 50% hatch time of 20-27 hours.
  
  *Larvae:*

Red snapper larvae are found throughout the Gulf in offshore waters at depths from 18-126 m (based on spawning adult depth distributions). They are water column associated and are most abundant from July through November at temperatures of 17.3-29.7&deg;C and salinities of 32.8-37.5 ppt. Their estimated pelagic larval duration is 28 days, and postlarvae settle at 16-19 mm TL. In the lab, larvae prey on alga and rotifers. 

  
  *Juveniles:*
 
Juveniles, both early and late, are found throughout the Gulf in nearshore and offshore waters and occupy reefs, hard bottom, banks/shoals, soft bottom, and sand/shell habitats. They have growth rates of approximately 0.817-1.01 mm/day. Early juveniles are found from July through November at temperatures of 17.3-29.7&deg;C, salinities of 30-35 ppt, dissolved oxygen (DO) concentrations greater than 0.4 mg/L, and depths from 17-183 m. Prey items include zooplankton, shrimp, chaetognaths, squid, and copepods. Late juveniles are found year-round at temperatures of 20-28&deg;C, salinities of 30-35 ppt, DO greater than 0.4 mg/L, and depths from 18-55 m. They prey on fish, squid, crabs and shrimp. Both early and late juveniles are subject to mortality via shrimp trawl bycatch and have natural mortalities (*M*) of 2.0/year (age 0) and 1.2/year (age 1). Despite not being considered essential fish habitat at this time, juvenile red snapper use artificial reefs as habitat.

  *Adults/Spawning Adults:*
  
Adult red snapper are found throughout the Gulf, year-round, in nearshore and offshore waters. They occupy reefs, hard bottom, and banks/shoal habitats at depths of 7-146 m, temperatures of 14-30&deg;C, and salinities of 33-37 ppt. Prey include fish, shrimp, squid, octopus, and crabs. One of their primary predators are sharks. They face mortality from a directed fishery, which they enter at age two, and *M* is estimated to be 0.094/year. Life history parameters have been estimated at L~inf~ (max. TL cm) = 85.64, *K* = 0.19, t~0~ = -0.39, and maximum age = 48 years. Spawning occurs in offshore waters on sand/shell and bank/shoal habitats from April through October at temperatures of 16-29&deg;C and depths of 18-126 m. 50% maturity occurs for females at age 3-5 and 400-450 mm TL, and 100% maturity occurs by age 8 and 700 mm TL. Batch fecundity has been estimated at 27-142 eggs/g (fish weight). Despite not being considered essential fish habitat at this time, adult red snapper use artificial reefs as habitat.

<!--####Fishery History

Red snapper harvest began in the 1840s, with effort being centered around Pensacola, FL (Collins 1887; Hood et al. 2007). Early fishing was limited to certain vessels and remained close to shore due to the transport limitations. As these limitations resolved via the increased assessibilitiy to trains and ice, vessels could travel further from shore and landings increased (Bortone et al. 1997; Hood et al. 2007). In the late 1800s, harvest began occuring off of Campeche Banks, Mexico (Camber 1955) and in the 1930s and 1940s, fishing pace picked up in the western Gulf upon discovery of rocky ridges and banks (Carpenter 1965). After World War II, technological advances allowed for further increases in commercial harvest (Porch et al. 2007; Siebenaler and Brady 1952). During this time, the shimp fishery was also expanding, and this fishery became a source of juvenile red snapper mortality. Similarly to the commercial fishery, the recreational fishery increased post-World War II due to increased tourism along the Gulf Coast and the invent of fiberglass boats (Walter 2006).

These rapid and largely unregulated increases in red snapper harvest led to the population reaching an all time low in 1990 (SEDAR 2009). In the late 1980s, the first management measures were implimented to reduce fishing mortality in an effort to rebuild the stock (Hood et al. 2007). A variety of measure have been used to decrease fishing effort both to the directed fishery and the shrimp trawl fishery. Rebuilding plans have been developed to aid in the recovery of the species, and have seemingly been successful. Currently the stock status is overfished, but not undergoing overfishing (SEDAR 2013). A more detailed explaination of the red snapper fishery and management history can be found at http://sero.nmfs.noaa.gov/sustainable_fisheries/gulf_fisheries/red_snapper/overview/.-->

